include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true

    avoid_dynamic_calls: true
    avoid_type_to_string: true

    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true

    require_trailing_commas: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    use_named_constants: true

    public_member_api_docs: true

    use_build_context_synchronously: true

    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true

    prefer_single_quotes: true
    unnecessary_string_interpolations: true
    unnecessary_raw_strings: true

    avoid_function_literals_in_foreach_calls: false
    prefer_expression_function_bodies: false