name: max_killer
description: "Max Killer"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  injectable: ^2.5.1
  pro_mpack: ^2.0.2
  ffi: ^2.1.4
  path: ^1.9.1
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true